from .error import router as error_router
from .prank import router as prank_router
from .shutdown import router as shutdown_router
from .takephoto import router as takephoto_router
from .upload_photo import router as uploadphoto_router
from .menu import router as menu_router
from .settings import router as settings_router
from .profile import router as profile_router
from .paginator import router as paginator_router
from .block_control import router as block_control_router
